import { Image as ImageIcon, Video } from "lucide-react";
import Image from "next/image";
import { WorkspacePageHeader } from "@/components/workspace/workspace-page-header";
import { Card, CardContent } from "@/components/ui/card";
import { getLatestMaterialBatch, getMaterialBatch } from "@/lib/materials";
import { MaterialsDropzone } from "@/components/workspace/materials-dropzone";
import { AnalyzeMaterialsButton } from "@/components/workspace/analyze-materials-button";
import { NewMaterialBatchButton } from "@/components/workspace/new-material-batch-button";

export default async function MaterialsPage({ searchParams }: { searchParams: Promise<{ batch?: string }> }) {
  const requested = (await searchParams).batch; const batch = requested ? await getMaterialBatch(requested).catch(() => null) : await getLatestMaterialBatch(); const counts = batch?.assets.reduce((value, asset) => ({ ...value, [asset.analysisStatus]: value[asset.analysisStatus] + 1 }), { READY: 0, ANALYZING: 0, ANALYZED: 0, FAILED: 0, UPLOADING: 0 }) || null;
  return <div className="mx-auto max-w-6xl p-5 sm:p-8 lg:p-10"><WorkspacePageHeader title="今日素材" description="把今天发生的事情放进来，AI 会帮你整理。" action={false} /><div className="grid gap-7 lg:grid-cols-[minmax(0,1fr)_280px]"><section>{batch?.assets.length ? <><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-muted-foreground">已保存 {batch.assets.length} 条素材 · {batch.status === "ANALYZED" ? "已整理" : "等待整理"}</p>{counts ? <p className="mt-1 text-xs text-muted-foreground">已理解 {counts.ANALYZED} · 处理中 {counts.ANALYZING} · 待处理 {counts.READY + counts.UPLOADING} · 失败 {counts.FAILED}</p> : null}</div><div className="flex gap-2"><NewMaterialBatchButton /><AnalyzeMaterialsButton batchId={batch.id} /></div></div><div className="grid gap-3 sm:grid-cols-2">{batch.assets.map((item) => <Card key={item.id}><CardContent className="flex items-center gap-4"><span className="flex size-11 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-primary/10 text-primary">{item.thumbnailUrl ? <Image src={item.thumbnailUrl} alt="素材缩略图" width={88} height={88} className="size-full object-cover" /> : item.type === "VIDEO" ? <Video className="size-5" /> : <ImageIcon className="size-5" />}</span><div className="min-w-0"><p className="font-medium">{item.type === "VIDEO" ? "视频素材" : "图片素材"}</p><p className="mt-1 text-xs text-muted-foreground">{item.duration ? `${item.duration.toFixed(1)} 秒 · ` : ""}{item.analysisStatus === "ANALYZED" ? item.analysis?.summary : item.analysisStatus === "FAILED" ? "处理失败" : "等待 AI 整理"}</p></div></CardContent></Card>)}</div></> : <Card><CardContent className="py-14 text-center"><Video className="mx-auto size-8 text-primary" /><h2 className="mt-4 font-semibold">还没有素材</h2><p className="mt-2 text-sm text-muted-foreground">先添加今天拍摄的视频或图片。</p><div className="mt-5"><NewMaterialBatchButton /></div></CardContent></Card>}</section><aside><MaterialsDropzone initialBatchId={batch?.id} /></aside></div></div>;
}
