"use client";
import { ChangeEvent, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export function CaptureTaskWorkflow({ productionId, task }: { productionId: string; task: { id: string; order: number; purpose: string; actionInstruction: string; cameraInstruction: string; targetDuration: number } }) {
  const [clip, setClip] = useState<File | null>(null); const [url, setUrl] = useState<string | null>(null); const [take, setTake] = useState<{ id: string; videoUrl: string } | null>(null); const [status, setStatus] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  function choose(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (file.size > 100 * 1024 * 1024) { setError("视频最大支持 100MB。"); return; } setError(null); setTake(null); setStatus(null); setClip(file); setUrl(URL.createObjectURL(file)); }
  async function upload() { if (!clip) return; setStatus("正在保存…"); const response = await fetch(`/api/productions/${productionId}/tasks/${task.id}/takes`, { method: "POST", headers: { "Content-Type": clip.type, "X-File-Name": encodeURIComponent(clip.name), "X-File-Size": String(clip.size) }, body: clip }); const body = await response.json(); if (!response.ok) { setError(body.error || "保存失败。"); setStatus(null); return; } setTake(body.take); setStatus("正在 AI 检查…"); const evaluation = await fetch(`/api/productions/${productionId}/tasks/${task.id}/takes/${body.take.id}/evaluation`, { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); const checked = await evaluation.json(); setStatus(evaluation.ok ? checked.status === "PASSED" ? "AI：通过" : "AI：建议重拍" : checked.error || "检查失败"); }
  async function accept() { if (!take) return; const response = await fetch(`/api/productions/${productionId}/tasks/${task.id}/takes/${take.id}/evaluation`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "accept" }) }); if (response.ok) setStatus("已采用这条"); }
  return <main className="mx-auto max-w-xl p-5 sm:p-8"><Link href={`/workspace/produce/${productionId}`} className="text-sm text-muted-foreground">返回制作方案</Link><p className="mt-6 text-sm text-muted-foreground">补拍 {task.order}</p><h1 className="mt-1 text-2xl font-bold">{task.purpose}</h1><section className="mt-5 space-y-4 rounded-2xl bg-white p-5 shadow-sm"><div><p className="text-xs text-muted-foreground">你要做什么</p><p>{task.actionInstruction}</p></div><div><p className="text-xs text-muted-foreground">手机怎么拍</p><p>{task.cameraInstruction}</p></div><p className="text-sm text-muted-foreground">目标约 {task.targetDuration} 秒</p></section>{url && <video src={url} controls autoPlay playsInline className="mt-5 aspect-[9/16] w-full rounded-2xl bg-black object-contain" />}<label className="mt-5 flex h-14 cursor-pointer items-center justify-center rounded-xl bg-primary font-medium text-white">拍摄或从相册选择视频<input className="sr-only" type="file" accept="video/*" capture="environment" onChange={choose} /></label>{clip && !take && <Button className="mt-3 w-full" onClick={() => void upload()}>使用这条并 AI 检查</Button>}{take && <Button className="mt-3 w-full" variant="outline" onClick={() => void accept()}>仍然使用这条</Button>}{status && <p className="mt-4 rounded-xl bg-workspace-soft p-3 text-sm">{status}</p>}{error && <p className="mt-4 text-sm text-red-700">{error}</p>}</main>;
}
