"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Download, Film, LoaderCircle, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { RenderSettings } from "@/components/render-settings";

type View = { projectName: string; eligible: boolean; missing: Array<{ id: string; order: number }>; sourceCount: number; finalVideo: null | { status: "PENDING" | "RENDERING" | "READY" | "FAILED" | "OUTDATED"; fileUrl: string | null; duration: number | null; width: number | null; height: number | null; fileSize: number | null; errorMessage: string | null; outdated: boolean } };
function filename(name: string) { return `${name.replace(/[\\/:*?"<>|]/g, "-").trim() || "ai-director"}-final.mp4`; }

export function FinalVideoPanel({ projectId, initial }: { projectId: string; initial: View }) {
  const [view, setView] = useState(initial); const [busy, setBusy] = useState(false); const rendering = view.finalVideo?.status === "RENDERING";
  useEffect(() => { if (view.finalVideo?.status === "READY" && view.finalVideo.fileUrl) void fetch(`/api/projects/${projectId}/analytics`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ eventName: "FINAL_VIDEO_VIEWED" }) }); }, [projectId, view.finalVideo?.status, view.finalVideo?.fileUrl]);
  useEffect(() => { if (!rendering) return; const timer = window.setInterval(() => void fetch(`/api/projects/${projectId}/final-video`).then((response) => response.ok ? response.json() : null).then((next: View | null) => { if (next) setView(next); }), 2000); return () => window.clearInterval(timer); }, [projectId, rendering]);
  async function render() { setBusy(true); try { const response = await fetch(`/api/projects/${projectId}/final-video`, { method: "POST" }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error || "这次没有成功生成成片。"); setView((current) => ({ ...current, finalVideo: { ...(current.finalVideo || { fileUrl: null, duration: null, width: null, height: null, fileSize: null, errorMessage: null, outdated: false }), status: "RENDERING", errorMessage: null } })); } catch (error) { setView((current) => ({ ...current, finalVideo: { ...(current.finalVideo || { fileUrl: null, duration: null, width: null, height: null, fileSize: null, outdated: false }), status: "FAILED", errorMessage: error instanceof Error ? error.message : "这次没有成功生成成片。" } })); } finally { setBusy(false); } }
  if (!view.eligible) return <section className="mt-8 rounded-2xl border border-border bg-card p-5"><h2 className="font-semibold">还不能生成成片</h2><p className="mt-2 text-sm text-muted-foreground">还有 {view.missing.length} 个镜头没有可用素材。</p><div className="mt-3 flex flex-wrap gap-2">{view.missing.map((shot) => <Button asChild size="sm" variant="outline" key={shot.id}><Link href={`/projects/${projectId}/shoot/${shot.id}`}>镜头 {shot.order}</Link></Button>)}</div></section>;
  if (rendering) return <section className="mt-8 rounded-2xl border border-border bg-card p-6 text-center"><LoaderCircle className="mx-auto size-7 animate-spin text-primary" /><h2 className="mt-3 font-semibold">正在生成你的第一版成片…</h2><p className="mt-2 text-sm text-muted-foreground">正在整理镜头、统一画面并合成视频。</p>{view.finalVideo?.fileUrl && <p className="mt-4 text-xs text-muted-foreground">上一版成片仍可播放。</p>}</section>;
  if (view.finalVideo?.status === "READY" && view.finalVideo.fileUrl) return <><section className="mt-8 rounded-2xl border border-border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">你的增强成片完成了</h2><p className="mt-1 text-sm text-muted-foreground">{view.finalVideo.outdated ? "你更新了镜头或设置，建议重新生成成片。" : `共 ${view.sourceCount} 镜 · ${view.finalVideo.duration?.toFixed(1)} 秒 · ${view.finalVideo.width}×${view.finalVideo.height}`}</p></div><Film className="size-5 text-primary" /></div><video src={view.finalVideo.fileUrl} controls playsInline className="mt-5 max-h-[70svh] w-full rounded-xl bg-black object-contain" /><div className="mt-4 grid grid-cols-2 gap-3"><Button variant="outline" disabled={busy} onClick={() => void render()}><RefreshCw />重新生成</Button><Button asChild><a href={view.finalVideo.fileUrl} download={filename(view.projectName)} onClick={() => void fetch(`/api/projects/${projectId}/analytics`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ eventName: "FINAL_VIDEO_DOWNLOADED" }) })}><Download />下载视频</a></Button></div></section><RenderSettings projectId={projectId} /></>;
  return <section className="mt-8 rounded-2xl border border-border bg-card p-6 text-center"><Film className="mx-auto size-8 text-primary" /><h2 className="mt-3 font-semibold">准备生成第一版成片</h2><p className="mt-2 text-sm text-muted-foreground">将按镜头顺序拼接 {view.sourceCount} 条当前采用的素材。</p>{view.finalVideo?.errorMessage && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">这次没有成功生成成片：{view.finalVideo.errorMessage}</p>}<Button className="mt-5" disabled={busy} onClick={() => void render()}>{busy ? <><LoaderCircle className="animate-spin" />正在创建任务…</> : "生成成片"}</Button></section>;
}
