"use client";
import { useEffect, useState } from "react";
import { Download, Film, LoaderCircle, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";

type View = { title: string; status: string; timeline: Array<{ order: number; sourceType: string; role: string; plannedDuration: number }>; finalVideo: null | { status: "PENDING" | "RENDERING" | "READY" | "FAILED" | "OUTDATED"; fileUrl: string | null; duration: number | null; fileSize: number | null; errorMessage: string | null; subtitleStatus: string | null; bgmEnabled: boolean; finalQaStatus: string | null; outdated: boolean } };
function filename(name: string) { return `${name.replace(/[\\/:*?"<>|]/g, "-").trim() || "ai-director"}-final.mp4`; }
export function ProductionFinalVideoPanel({ productionId, initial }: { productionId: string; initial: View }) {
  const [view, setView] = useState(initial); const [busy, setBusy] = useState(false); const rendering = view.finalVideo?.status === "RENDERING";
  useEffect(() => { if (view.finalVideo?.status === "READY" && view.finalVideo.fileUrl) void fetch(`/api/productions/${productionId}/analytics`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ eventName: "CONTENT_FINAL_VIDEO_VIEWED" }) }); }, [productionId, view.finalVideo?.status, view.finalVideo?.fileUrl]);
  useEffect(() => { if (!rendering) return; const timer = window.setInterval(() => void fetch(`/api/productions/${productionId}/final-video`).then((response) => response.ok ? response.json() : null).then((next: View | null) => next && setView(next)), 2000); return () => window.clearInterval(timer); }, [productionId, rendering]);
  async function render() { setBusy(true); try { const response = await fetch(`/api/productions/${productionId}/final-video`, { method: "POST" }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error || "这次没有成功生成成片。"); setView((current) => ({ ...current, finalVideo: { ...(current.finalVideo || { fileUrl: null, duration: null, fileSize: null, subtitleStatus: null, bgmEnabled: false, finalQaStatus: null, outdated: false, errorMessage: null }), status: "RENDERING", errorMessage: null } })); } catch (error) { setView((current) => ({ ...current, finalVideo: { ...(current.finalVideo || { fileUrl: null, duration: null, fileSize: null, subtitleStatus: null, bgmEnabled: false, finalQaStatus: null, outdated: false, errorMessage: null }), status: "FAILED", errorMessage: error instanceof Error ? error.message : "这次没有成功生成成片。" } })); } finally { setBusy(false); } }
  async function setBgm(bgmEnabled: boolean) { setBusy(true); try { const response = await fetch(`/api/productions/${productionId}/final-video/settings`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ bgmEnabled }) }); if (!response.ok) throw new Error(); setView((current) => current.finalVideo ? { ...current, finalVideo: { ...current.finalVideo, bgmEnabled, outdated: true, status: "OUTDATED" } } : current); } finally { setBusy(false); } }
  const ready = (view.finalVideo?.status === "READY" || view.finalVideo?.status === "OUTDATED") && view.finalVideo.fileUrl;
  return <section className="mt-6 rounded-2xl border bg-white p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">自动成片</h2><p className="mt-1 text-sm text-muted-foreground">{view.timeline.length} 个确定顺序的片段 · 字幕与背景音乐在合成后统一处理。</p></div><Film className="size-5 text-primary" /></div>{rendering && <><div className="mt-5 rounded-xl bg-workspace-soft p-4 text-sm"><LoaderCircle className="mr-2 inline size-4 animate-spin" />正在生成视频；上一版文件会保留。</div>{view.finalVideo?.fileUrl && <video src={view.finalVideo.fileUrl} controls playsInline className="mt-5 max-h-[70svh] w-full rounded-xl bg-black object-contain" />}</>}{ready && <><video src={view.finalVideo!.fileUrl!} controls playsInline className="mt-5 max-h-[70svh] w-full rounded-xl bg-black object-contain" /><p className="mt-3 text-sm text-muted-foreground">{view.finalVideo!.duration?.toFixed(1)} 秒 · 字幕：{view.finalVideo!.subtitleStatus || "未生成"} · 背景音乐：{view.finalVideo!.bgmEnabled ? "开启" : "关闭"} · 质检：{view.finalVideo!.finalQaStatus || "等待中"}</p><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={view.finalVideo!.bgmEnabled} disabled={busy || rendering} onChange={(event) => void setBgm(event.target.checked)} />背景音乐</label><div className="mt-3 grid grid-cols-2 gap-3"><Button variant="outline" disabled={busy || rendering} onClick={() => void render()}><RefreshCw />重新生成</Button><Button asChild><a href={view.finalVideo!.fileUrl!} download={filename(view.title)} onClick={() => void fetch(`/api/productions/${productionId}/analytics`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ eventName: "CONTENT_FINAL_VIDEO_DOWNLOADED" }) })}><Download />下载视频</a></Button></div>{view.finalVideo!.outdated && <p className="mt-3 text-sm text-amber-700">素材或采用视频已变化，请重新生成成片。</p>}</>}{!ready && !rendering && <><p className="mt-4 text-sm text-muted-foreground">生成时会检查每个素材、时长与本地文件是否可用。</p>{view.finalVideo?.errorMessage && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{view.finalVideo.errorMessage}</p>}<Button className="mt-5" disabled={busy} onClick={() => void render()}>{busy ? <><LoaderCircle className="animate-spin" />正在创建任务…</> : "生成视频"}</Button></>}</section>;
}
