import "dotenv/config";
import { stat } from "node:fs/promises";
import path from "node:path";
import { getMaterialAIConfig } from "../packages/ai/get-material-ai-provider";
import { KieMaterialAIProvider } from "../packages/ai/providers/kie-material-ai-provider";
import { WorkflowError } from "../lib/errors";

const isVideo = process.argv.includes("--video");
const file = path.resolve(isVideo ? "test-fixtures/step10b-video/cardigan-lift.mp4" : `test-fixtures/step10b-smoke/${process.argv.includes("--second-image") ? "a-unbox.png" : process.argv.includes("--third-image") ? "c-rack.png" : "b-cardigan.png"}`);
const mimeType = isVideo ? "video/mp4" : "image/png";
async function main() {
  const info = await stat(file); const config = getMaterialAIConfig(); const started = Date.now();
  if (process.argv.includes("--plain")) { const provider = new KieMaterialAIProvider({ apiKey: process.env.KIE_API_KEY || "", model: config.model || "" }); const result = await provider.diagnosePlainText(file, "image/png"); console.log(JSON.stringify({ httpClient: "fetch", httpStatus: 200, httpCallResultShape: result.shape, parserInputShape: result.shape, unwrapPath: "none", testARequestSent: "YES", testATextExtracted: "YES", testAMatchedOK: result.matchedOk ? "YES" : "NO" }, null, 2)); return; }
  if (process.argv.includes("--minimal-json")) { const provider = new KieMaterialAIProvider({ apiKey: process.env.KIE_API_KEY || "", model: config.model || "" }); const result = await provider.diagnoseMinimalJson(file, "image/png"); console.log(JSON.stringify({ testBRequestSent: "YES", jsonParseStatus: "PASS", zodStatus: "PASS", ...result }, null, 2)); return; }
  if (process.argv.includes("--structured")) { const provider = new KieMaterialAIProvider({ apiKey: process.env.KIE_API_KEY || "", model: config.model || "" }); const result = await provider.diagnoseStructuredOutput(file, "image/png"); console.log(JSON.stringify({ testCRequestSent: "YES", responseFormatPresent: "YES", responseFormatType: "json_schema", textExtraction: "PASS", jsonParse: "PASS", zod: "PASS", parsedTopLevelKeys: Object.keys(result.result), materialAnalysisResult: "YES", ...result }, null, 2)); return; }
  if (process.argv.includes("--prompt-json")) { const provider = new KieMaterialAIProvider({ apiKey: process.env.KIE_API_KEY || "", model: config.model || "" }); const result = await provider.diagnosePromptJsonOutput(file, mimeType, isVideo); console.log(JSON.stringify({ provider: "KIE", model: config.model, structuredOutputMode: provider.structuredOutputMode, responseFormatSent: "NO", upload: "PASS", modelStatus: "PASS", textExtraction: "PASS", jsonParse: "PASS", zod: "PASS", materialAnalysis: "YES", ...result }, null, 2)); return; }
  const output: Record<string, unknown> = { file: { type: "image", mime: "image/png", size: info.size }, config: { provider: config.provider, model: config.model }, upload: { status: "UNKNOWN", attempts: null, durationMs: null }, model: { requestSent: "YES", status: "UNKNOWN", attempts: null, durationMs: null }, response: { rawResponseReceived: "NO", structuredJsonReceived: "NO" }, schema: { zodValidation: "FAIL" }, result: { materialAnalysisCreated: "NO" }, failureStage: "UNKNOWN", errorCategory: "OTHER" };
  try { const result = new KieMaterialAIProvider({ apiKey: process.env.KIE_API_KEY || "", model: config.model || "" }); const analyzed = await result.analyzeMaterial({ assetId: "smoke-cardigan-jpg", localFilePath: file, mimeType: "image/png", type: "IMAGE", duration: null }); output.upload = { status: "PASS", httpStatus: 200, attempts: 1, durationMs: Date.now() - started }; output.model = { requestSent: "YES", status: "PASS", httpStatus: 200, attempts: 1, durationMs: Date.now() - started }; output.response = { rawResponseReceived: "YES", structuredJsonReceived: "YES" }; output.schema = { zodValidation: "PASS" }; output.result = { materialAnalysisCreated: "YES", ...analyzed }; output.failureStage = "NONE"; output.errorCategory = "NONE"; }
  catch (error) { const cause = error instanceof WorkflowError ? error.cause as { status?: number } | undefined : undefined; const code = error instanceof WorkflowError ? error.code : "UNKNOWN"; const status = cause?.status || null; output.upload = { status: code === "UPLOAD_FAILED" ? "FAIL" : "UNKNOWN", httpStatus: status, attempts: status && status < 500 && status !== 429 ? 1 : 3, durationMs: Date.now() - started }; output.model = { requestSent: code !== "UPLOAD_FAILED" ? "YES" : "NO", status: code === "PROVIDER_REQUEST_FAILED" ? "FAIL" : "UNKNOWN", httpStatus: status, attempts: status && status < 500 && status !== 429 ? 1 : 3, durationMs: Date.now() - started }; output.failureStage = code === "UPLOAD_FAILED" ? "UPLOAD" : code === "PROVIDER_REQUEST_FAILED" ? "MODEL" : "SCHEMA"; output.errorCategory = status === 429 ? "429" : status && status >= 500 ? "5XX" : status && status >= 400 ? "4XX" : code === "ProviderResponseInvalid" ? "INVALID_RESPONSE" : "OTHER"; }
  console.log(JSON.stringify(output, null, 2));
}
void main();
