import "dotenv/config";
import { db } from "../lib/db";
import { DEMO_USER_ID } from "../lib/demo-user";
import { ensureDemoUser } from "../lib/demo-user";
import { recordProductEvent, recordUsage } from "../lib/analytics";
import { AnalyticsEvent } from "../lib/analytics-events";
import { mkdir, writeFile } from "node:fs/promises";

async function main() { await ensureDemoUser(); const project = await db.project.create({ data: { userId: DEMO_USER_ID, name: "Internal Step 9 Smoke", status: "COMPLETED", finalVideo: { create: { status: "READY", duration: 1, width: 720, height: 1280, fps: 30, codec: "h264", fileSize: 1 } } } }); const session = await db.userTestSession.create({ data: { userId: DEMO_USER_ID, projectId: project.id, testerLabel: "Internal Tester", testerType: "CREATOR", experienceLevel: "INTERMEDIATE", intendedContent: "内部完整流程验证", pricingVariant: "B", status: "COMPLETED", completedAt: new Date() } }); for (const eventName of [AnalyticsEvent.PROJECT_CREATED, AnalyticsEvent.REFERENCE_VIDEO_UPLOAD_COMPLETED, AnalyticsEvent.REFERENCE_ANALYSIS_COMPLETED, AnalyticsEvent.SHOOTING_PLAN_COMPLETED, AnalyticsEvent.TAKE_UPLOADED, AnalyticsEvent.FINAL_RENDER_COMPLETED, AnalyticsEvent.FINAL_VIDEO_VIEWED, AnalyticsEvent.FINAL_VIDEO_DOWNLOADED, AnalyticsEvent.PRICING_PLAN_SELECTED]) await recordProductEvent({ eventName, projectId: project.id, sessionId: session.id }); await db.testFeedback.create({ data: { testSessionId: session.id, priorAbility: "勉强可以", mostHelpful: "逐镜拍摄指导", mostDifficult: "拍完 AI 检查", reuseIntent: "可能会", publishIntent: "稍微改一下会发布", recommendScore: 8 } }); await db.userTestSession.update({ where: { id: session.id }, data: { selectedPlan: "CREATOR" } }); await recordUsage({ projectId: project.id, operation: "SPEECH_TO_TEXT", provider: "local", model: "base", durationMs: 100, currencyCost: 0 }); const result = { sessionId: session.id, projectId: project.id, selectedPlan: "CREATOR", feedback: true, eventCount: 9 }; await mkdir("test-results", { recursive: true }); await writeFile("test-results/step9-smoke.json", JSON.stringify(result, null, 2)); console.log(JSON.stringify(result, null, 2)); await db.$disconnect(); }
void main();
