import "server-only";
import { openAsBlob } from "node:fs";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { WorkflowError } from "../../../lib/errors";
import { logEvent } from "../../../lib/logger";
import type { MaterialUnderstandingProvider } from "../material-ai-provider";

export const materialAnalysisSchema = z.object({ summary: z.string().min(1).max(600), scene: z.string().max(200).nullable(), activity: z.string().max(200).nullable(), objects: z.array(z.string().max(100)).max(20), topics: z.array(z.string().max(100)).max(10), speechSummary: z.string().max(500).nullable(), visualQuality: z.enum(["GOOD", "USABLE", "POOR"]), storyPotential: z.number().int().min(0).max(100), confidence: z.number().min(0).max(1) });
const minimalSummarySchema = z.object({ summary: z.string().min(1) });
const eventPlanSchema = z.object({ title: z.string().min(1).max(160), summary: z.string().min(1).max(600), assetIds: z.array(z.string()).min(1), confidence: z.number().min(0).max(1), reason: z.string().min(1).max(600) });
const eventsSchema = z.object({ contentThreads: z.array(eventPlanSchema).max(8), events: z.array(eventPlanSchema).max(8), unassignedAssetIds: z.array(z.string()) });
const opportunitiesSchema = z.object({ opportunities: z.array(z.object({ title: z.string().min(1).max(180), contentType: z.enum(["PRODUCT", "DAILY_VLOG", "STORY", "KNOWLEDGE", "BEHIND_THE_SCENES", "OTHER"]), angle: z.string().min(1).max(400), summary: z.string().min(1).max(800), hook: z.string().min(1).max(400), targetDuration: z.number().min(5).max(120), reason: z.string().min(1).max(800), assetIds: z.array(z.string()).min(1), missing: z.array(z.object({ purpose: z.string().min(1), actionInstruction: z.string().min(1), cameraInstruction: z.string().min(1), targetDuration: z.number().min(1).max(20), reason: z.string().min(1).max(800) })).max(3) })).max(3) });

export function extractKieUploadedMediaUrl(response: unknown) {
  const data = response && typeof response === "object" ? (response as { data?: unknown }).data : null;
  const candidate = data && typeof data === "object" ? (data as { downloadUrl?: unknown; fileUrl?: unknown }).downloadUrl ?? (data as { fileUrl?: unknown }).fileUrl : null;
  if (typeof candidate !== "string" || !/^https?:\/\//i.test(candidate)) throw new WorkflowError("INVALID_UPLOAD_RESPONSE", "素材 AI 上传响应无有效媒体地址。", 502);
  return candidate;
}
export function extractKieAssistantText(response: unknown) {
  const value = response as { choices?: { message?: { content?: unknown } }[]; candidates?: { content?: { parts?: { text?: unknown; thought?: unknown }[] } }[]; };
  const openAi = value?.choices?.[0]?.message?.content;
  if (typeof openAi === "string" && openAi.trim()) return openAi;
  const gemini = value?.candidates?.[0]?.content?.parts?.filter((part) => !part.thought && typeof part.text === "string").map((part) => part.text).join("");
  if (typeof gemini === "string" && gemini.trim()) return gemini;
  throw new WorkflowError("PROVIDER_INVALID_RESPONSE", "素材 AI 返回无有效内容。", 422);
}
export function inspectObjectShape(value: unknown, depth = 3): unknown {
  if (depth < 0 || value === null) return { $type: value === null ? "null" : typeof value };
  if (Array.isArray(value)) return { $type: "array", length: value.length, items: value.slice(0, 1).map((item) => inspectObjectShape(item, depth - 1)) };
  if (typeof value !== "object") return { $type: typeof value };
  return { $type: "object", keys: Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([key, item]) => [key, inspectObjectShape(item, depth - 1)])) };
}

export class KieMaterialAIProvider implements MaterialUnderstandingProvider {
  readonly structuredOutputMode = "prompt_json" as const;
  constructor(private readonly config: { apiKey: string; model: string }) {}
  private async post(url: string, body: BodyInit, json = false, stage = "UNKNOWN") { let last: Error | undefined; for (let attempt = 0; attempt < 3; attempt += 1) { try { const response = await fetch(url, { method: "POST", headers: { Authorization: `Bearer ${this.config.apiKey}`, ...(json ? { "Content-Type": "application/json" } : {}) }, body, signal: AbortSignal.timeout(300000) }); const text = await response.text(); if (!response.ok) { const error = new Error(`HTTP ${response.status}`) as Error & { status?: number }; error.status = response.status; throw error; } return JSON.parse(text); } catch (error) { last = error as Error; logEvent("material_ai.attempt_failed", { stage, attempt: attempt + 1, httpStatus: (error as { status?: number }).status || null }); const status = (error as { status?: number }).status; if (attempt < 2 && (!status || status === 429 || status >= 500)) await new Promise((resolve) => setTimeout(resolve, 500 * 2 ** attempt)); else break; } } throw new WorkflowError(stage === "UPLOAD" ? "UPLOAD_FAILED" : "PROVIDER_REQUEST_FAILED", "素材 AI 服务暂时不可用，请稍后重试。", 502, { cause: last }); }
  private async chat(prompt: string, schema: object, mediaUrl?: string) { const body = { model: this.config.model, stream: false, messages: [{ role: "system", content: "只陈述可观察事实。禁止推断人物身份、成交、销量、地点、情绪、关系或未听到的对白。返回严格 JSON。" }, { role: "user", content: mediaUrl ? [{ type: "text", text: prompt }, { type: "image_url", image_url: { url: mediaUrl } }] : prompt }], response_format: { type: "json_schema", json_schema: { name: "material_result", strict: true, schema } } }; const response = await this.post(`https://api.kie.ai/${this.config.model}-openai/v1/chat/completions`, JSON.stringify(body), true, "MODEL"); const text = extractKieAssistantText(response); return { text, value: JSON.parse(text) }; }
  private async promptJson<T>(prompt: string, schema: z.ZodType<T>) { const body = { model: this.config.model, stream: false, messages: [{ role: "user", content: `只返回一个 JSON object。禁止 Markdown、代码围栏、解释文字和 JSON 前后额外文本。${prompt}` }] }; const response = await this.post(`https://api.kie.ai/${this.config.model}-openai/v1/chat/completions`, JSON.stringify(body), true, "MODEL"); let text: string; try { text = extractKieAssistantText(response); } catch (error) { logEvent("material_ai.text_response_shape", { shape: inspectObjectShape(response) }); throw error; } return schema.parse(JSON.parse(text)); }
  private async upload(path: string, mimeType: string) { const extension = mimeType === "image/jpeg" ? "jpg" : mimeType === "image/png" ? "png" : mimeType === "image/webp" ? "webp" : mimeType === "video/quicktime" ? "mov" : mimeType === "video/webm" ? "webm" : "mp4"; const form = new FormData(); form.append("file", await openAsBlob(path, { type: mimeType }), `${randomUUID()}.${extension}`); form.append("uploadPath", "ai-director/material-benchmark"); const result = await this.post("https://kieai.redpandaai.co/api/file-stream-upload", form, false, "UPLOAD"); if (process.env.NODE_ENV !== "production") logEvent("material_ai.upload_shape", { responseKeys: Object.keys(result || {}), dataKeys: result?.data && typeof result.data === "object" ? Object.keys(result.data) : [], dataTypes: result?.data && typeof result.data === "object" ? Object.fromEntries(Object.entries(result.data).map(([key, value]) => [key, typeof value])) : {} }); return extractKieUploadedMediaUrl(result); }
  async diagnosePlainText(localFilePath: string, mimeType: string) { const mediaUrl = await this.upload(localFilePath, mimeType); const body = { model: this.config.model, stream: false, messages: [{ role: "user", content: [{ type: "text", text: "只回复 OK" }, { type: "image_url", image_url: { url: mediaUrl } }] }] }; const response = await this.post(`https://api.kie.ai/${this.config.model}-openai/v1/chat/completions`, JSON.stringify(body), true, "MODEL"); const shape = inspectObjectShape(response); const text = extractKieAssistantText(response); return { shape, matchedOk: text.trim() === "OK" }; }
  async diagnoseMinimalJson(localFilePath: string, mimeType: string) { const mediaUrl = await this.upload(localFilePath, mimeType); const body = { model: this.config.model, stream: false, messages: [{ role: "system", content: "只输出 JSON，不要 Markdown、代码围栏或解释。只描述可观察事实。" }, { role: "user", content: [{ type: "text", text: "返回 {\"summary\":\"一句话客观描述图片\"}" }, { type: "image_url", image_url: { url: mediaUrl } }] }] }; const response = await this.post(`https://api.kie.ai/${this.config.model}-openai/v1/chat/completions`, JSON.stringify(body), true, "MODEL"); const text = extractKieAssistantText(response); const value = minimalSummarySchema.parse(JSON.parse(text)); return { assistantTextLength: text.length, startsWithBrace: text.trimStart().startsWith("{"), endsWithBrace: text.trimEnd().endsWith("}"), containsMarkdownFence: text.includes("```"), summary: value.summary }; }
  private async promptJsonMaterial(mediaUrl: string, isVideo = false, repair = false) { const prompt = `${repair ? "上一次输出不符合要求。请重新输出完整 JSON。不要解释、不要 Markdown，必须符合指定字段和类型。\n" : ""}只返回一个 JSON object。禁止 Markdown、代码围栏、解释文字和 JSON 前后额外文本。所有字段遵循：可观察事实优先于保守描述，保守描述优先于推断；不能确认时使用更保守的描述，不要为了具体而补全不存在的信息。只描述素材直接支持的事实；禁止推断新品、到货、热销、价格、销量、顾客评价、人物身份、材质成分、家庭关系、交易结果或未发生的动作。不要推断可见现象的来源：有光影只能描述“画面存在明暗光影”，不能写自然光、阳光或窗外采光，除非光源本身可见或有直接证据。不要推断物体或场景的用途：衣服、纸盒和包装纸同框时，不能写商品包装、发货、收货、快递或新品开箱。不要从当前状态推断之前或之后的事情：衣服在盒中不能写刚到货、正在拆包或准备上架。${isVideo ? "对于视频，可以描述时间范围内直接观察到的动作变化；不要从动作结果反推此前原因，也不要预测之后会发生什么。" : ""}不得增加其他字段。字段：summary（string，客观描述素材发生了什么）；scene（string 或 null，只描述画面可见的环境和空间特征，不描述光源原因、商业用途、真实场所身份或拍摄目的；若只看到纯色背景，写“纯色背景单品展示”，不要写“摄影棚”；无法确定地点时宁可使用视觉描述）；activity（string 或 null，只写直接观察到的主要行为或状态，不写正在拍摄商品图、准备上架或新品展示等推断）；objects（string[]，仅可见的重要物体）；topics（string[]，概括素材主题，不加入营销判断、商业用途或事件结果）；speechSummary（string 或 null）；visualQuality（只能是 GOOD、USABLE 或 POOR）；storyPotential（0 到 100 的整数，表示素材组成内容的信息价值，不是爆款概率）；confidence（0 到 1 的数字）。`;
    const body = { model: this.config.model, stream: false, messages: [{ role: "user", content: [{ type: "text", text: prompt }, { type: "image_url", image_url: { url: mediaUrl } }] }] };
    const response = await this.post(`https://api.kie.ai/${this.config.model}-openai/v1/chat/completions`, JSON.stringify(body), true, "MODEL");
    const text = extractKieAssistantText(response);
    return { text, result: materialAnalysisSchema.parse(JSON.parse(text)) };
  }
  async diagnoseStructuredOutput(localFilePath: string, mimeType: string) { const mediaUrl = await this.upload(localFilePath, mimeType); const response = await this.chat("分析这张图片。", materialAnalysisSchema, mediaUrl); const result = materialAnalysisSchema.parse(response.value); return { assistantTextLength: response.text.length, startsWithBrace: response.text.trimStart().startsWith("{"), endsWithBrace: response.text.trimEnd().endsWith("}"), containsMarkdownFence: response.text.includes("```"), result }; }
  private async promptJsonMaterialWithRepair(mediaUrl: string, isVideo = false) { let repairRetryUsed = false; try { const response = await this.promptJsonMaterial(mediaUrl, isVideo); return { ...response, repairRetryUsed }; } catch (error) { if (!(error instanceof SyntaxError) && !(error instanceof z.ZodError)) throw error; repairRetryUsed = true; return { ...(await this.promptJsonMaterial(mediaUrl, isVideo, true)), repairRetryUsed }; } }
  async diagnosePromptJsonOutput(localFilePath: string, mimeType: string, isVideo = false) { const mediaUrl = await this.upload(localFilePath, mimeType); const response = await this.promptJsonMaterialWithRepair(mediaUrl, isVideo); return { assistantTextLength: response.text.length, startsWithBrace: response.text.trimStart().startsWith("{"), endsWithBrace: response.text.trimEnd().endsWith("}"), containsMarkdownFence: response.text.includes("```"), repairRetryUsed: response.repairRetryUsed, result: response.result }; }
  async analyzeMaterial(input: Parameters<MaterialUnderstandingProvider["analyzeMaterial"]>[0]) { const url = await this.upload(input.localFilePath, input.mimeType); return (await this.promptJsonMaterialWithRepair(url, input.type === "VIDEO")).result; }
  async clusterEvents(input: Parameters<MaterialUnderstandingProvider["clusterEvents"]>[0]) { return this.promptJson(`这是纯文本推理任务，不要上传或假设原始媒体。先建立 ContentThread：它表示围绕同一主体、商品、人物或内容主题的素材集合，不表示同一次真实发生过程。再建立 StoryEvent：它只表示有足够直接证据支持为同一次真实过程的素材集合。确认 StoryEvent 至少需要一种强证据：capturedAtReliability 为 RELIABLE 的连续时间、明显动作连续性、同一可识别过程、明确用户上下文或其他直接事件边界。capturedAtReliability 为 WEAK 的时间只能辅助，NONE 不得推导时间线。仅 topic、scene 或 object 相同不足以确认 StoryEvent；这种素材可只进入 ContentThread。一个 event 的 assetIds 必须全部属于某个 ContentThread 的 assetIds。每个 assetId 必须恰好出现在 contentThreads[].assetIds 或 unassignedAssetIds 之一。没有明确关系时宁可 unassigned。不得编造时间、动作、到货、销售、人物身份、地点或因果。返回结构：{contentThreads:[{title,summary,assetIds,confidence,reason}],events:[{title,summary,assetIds,confidence,reason}],unassignedAssetIds:string[]}。\n${JSON.stringify(input)}`, eventsSchema); }
  async discoverOpportunities(input: Parameters<MaterialUnderstandingProvider["discoverOpportunities"]>[0]) { const result = await this.promptJson(`这是纯文本推理任务，不要上传或假设原始媒体。基于素材事实、ContentThreads、已确认 StoryEvents 和用户目标，最多给出三条基于证据的内容机会；允许少于三条。内容机会可以来自 ContentThread，不要求每条机会都有 StoryEvent。不得编造新品、到货、销售、顾客、试穿、人物态度或因果。每条 assetIds 只能引用输入中的现有 ID，且绝不能引用 unassignedAssetIds 中的 ID。contentType 必须是 PRODUCT、DAILY_VLOG、STORY、KNOWLEDGE、BEHIND_THE_SCENES、OTHER 之一。targetDuration 与 missing[].targetDuration 必须是不带单位的 JSON number。missing 为缺少素材时的手机可执行补拍建议，包含 purpose、actionInstruction、cameraInstruction、targetDuration、reason；若无需补拍则为空数组。若一条机会只引用一或两条素材，missing 必须提供一到三条具体补拍建议，补足该机会仍缺的画面。返回结构：{opportunities:[{title,contentType,angle,summary,hook,targetDuration,reason,assetIds,missing}]}。\n${JSON.stringify(input)}`, opportunitiesSchema); return result.opportunities; }
}
