ALTER TYPE "FinalVideoStatus" RENAME VALUE 'PROCESSING' TO 'RENDERING';
ALTER TYPE "FinalVideoStatus" RENAME VALUE 'COMPLETED' TO 'READY';

ALTER TABLE "FinalVideo"
  ALTER COLUMN "fileUrl" DROP NOT NULL,
  ADD COLUMN "storageKey" TEXT,
  ADD COLUMN "duration" DOUBLE PRECISION,
  ADD COLUMN "width" INTEGER,
  ADD COLUMN "height" INTEGER,
  ADD COLUMN "fps" DOUBLE PRECISION,
  ADD COLUMN "codec" TEXT,
  ADD COLUMN "fileSize" INTEGER,
  ADD COLUMN "sourceSnapshot" JSONB,
  ADD COLUMN "errorMessage" TEXT,
  ADD COLUMN "renderToken" TEXT,
  ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX "FinalVideo_renderToken_key" ON "FinalVideo"("renderToken");

ALTER TABLE "FinalVideo" ALTER COLUMN "updatedAt" DROP DEFAULT;
