import Link from "next/link";
import Image from "next/image";
import { ArrowRight, CalendarDays, FolderPlus, PackagePlus, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { EditCard, EmptyWorkspace, ShootCard, VideoCard, dateLabel, durationLabel } from "@/components/workspace/workspace-cards";
import { getWorkspaceDashboard } from "@/lib/workspace-dashboard";

export default async function WorkspacePage() {
  const data = await getWorkspaceDashboard();
  const hasContent = data.materials.length || data.activeProjects.length || data.recentVideos.length || data.editingProjects.length;
  const today = new Intl.DateTimeFormat("zh-CN", { month: "long", day: "numeric", weekday: "long", timeZone: "Asia/Shanghai" }).format(new Date());
  return <div className="mx-auto max-w-[1480px] p-5 sm:p-8 lg:p-10">
    <header className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-sm text-muted-foreground">早上好 👋</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">今天想完成什么内容？</h1><p className="mt-3 text-sm text-muted-foreground">AI 已为你整理今天的内容工作</p></div><div className="flex items-center gap-3"><span className="hidden items-center gap-2 text-sm text-muted-foreground sm:flex"><CalendarDays className="size-4" />{today}</span><Button asChild><Link href="/projects/new"><FolderPlus />上传素材</Link></Button></div></header>
    {!hasContent ? <section className="mt-10 grid gap-5 lg:grid-cols-2"><EmptyWorkspace title="我想拍一个这样的" description="上传一个参考视频，AI 帮你拆解并一步一步教你拍。" action={<Button asChild><Link href="/projects/new">上传参考视频<ArrowRight /></Link></Button>} /><EmptyWorkspace title="看看我今天能发什么" description="上传今天拍的视频和图片，AI 帮你发现值得发布的内容。" action={<Button asChild variant="outline"><Link href="/workspace/materials">添加今日素材<PackagePlus /></Link></Button>} /></section> : <div className="mt-10 grid gap-7 xl:grid-cols-[minmax(0,1fr)_320px]">
      <div className="min-w-0 space-y-9">
        <section><div className="mb-4 flex items-end justify-between gap-3"><div><h2 className="text-xl font-bold">今日素材</h2><p className="mt-1 text-sm text-muted-foreground">{data.materials.length} 个近期素材</p></div><Link className="text-sm font-medium text-primary" href="/workspace/materials">查看全部 →</Link></div>{data.materials.length ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{data.materials.slice(0, 8).map((item) => <Card key={item.id}><div className="relative aspect-[4/3] overflow-hidden bg-workspace-soft">{item.coverUrl ? <Image src={item.coverUrl} alt="视频素材参考画面" width={320} height={240} className="size-full object-cover" /> : <div className="flex size-full items-center justify-center"><Sparkles className="size-6 text-primary" /></div>}<span className="absolute bottom-2 left-2 rounded-md bg-black/70 px-1.5 py-1 text-[11px] text-white">{durationLabel(item.duration)}</span></div><CardContent className="p-3"><p className="text-xs font-medium">视频</p><p className="mt-1 text-[11px] text-muted-foreground">{dateLabel(item.createdAt)}</p></CardContent></Card>)}</div> : <EmptyWorkspace title="还没有今日素材" description="从一个参考视频开始，AI 会帮你完成后续拍摄。" action={<Button asChild size="sm"><Link href="/projects/new">上传参考视频</Link></Button>} />}</section>
        <section><div className="mb-4"><h2 className="text-xl font-bold">AI 发现的内容机会</h2><p className="mt-1 text-sm text-muted-foreground">基于你的素材，推荐值得制作的内容</p></div><EmptyWorkspace title="还没有发现内容机会" description="添加今天的素材后，AI 会在这里给你建议。" action={<Button asChild size="sm" variant="outline"><Link href="/workspace/materials">添加今日素材</Link></Button>} /></section>
        <section><div className="mb-4 flex items-end justify-between"><div><h2 className="text-xl font-bold">最近成片</h2><p className="mt-1 text-sm text-muted-foreground">可以随时查看或下载</p></div><Link className="text-sm font-medium text-primary" href="/workspace/videos">查看全部 →</Link></div>{data.recentVideos.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data.recentVideos.slice(0, 6).map((project) => <VideoCard key={project.id} project={project} />)}</div> : <EmptyWorkspace title="还没有成片" description="完成拍摄后，AI 会在这里整理你的成片。" />}</section>
      </div>
      <aside className="space-y-5"><section><h2 className="mb-4 text-lg font-bold">正在进行</h2>{data.activeProjects.length || data.editingProjects.length ? <div className="space-y-3">{data.activeProjects.map((project) => <ShootCard key={project.id} project={project} />)}{data.editingProjects.map((project) => <EditCard key={project.id} project={project} />)}</div> : <EmptyWorkspace title="今天还没有进行中的内容" description="从一个参考开始，完成你的第一条内容。" />}</section><Card className="bg-primary text-primary-foreground"><CardContent><p className="text-sm font-medium text-white/80">拍摄导演</p><h2 className="mt-2 text-lg font-semibold">从灵感到成片，每一步都有下一步。</h2><Button asChild size="sm" variant="outline" className="mt-5 border-white/30 bg-white text-primary hover:bg-white/90"><Link href="/workspace/shoot">查看拍摄任务</Link></Button></CardContent></Card></aside>
    </div>}
  </div>;
}
